### ISSUE TITLE
Drop setup requirement of eggtestinfo

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.publication#12]
It should not be needed, as it was dropped on other zopefoundation packages, too.

**Comment by janjaapdriessen** [comment]
Done in #14 - shall we also remove zope.testrunnner from `setup_requires`?

Also in https://github.com/zopefoundation/zope.app.appsetup/pull/5

**Comment by icemac** [comment]
If we drop `test_suite` and `test_loader`, `zope.testrunner` can also be dropped from `setup_requires`. This stops `python setup.py test` from working – this is no problem as it is discouraged by the `setuptools` developers and we already dropped it from many other repositories as well.

**Comment by janjaapdriessen** [comment]
Should we remove the `eggtestinfo` reference from [zope.testrunner](https://github.com/zopefoundation/zope.testrunner/blob/master/src/zope/testrunner/eggsupport.py#L48) as well? I am not familiar with zope.testrunner.

**Comment by mgedmin** [comment]
> Should we remove the eggtestinfo reference from zope.testrunner as well? I am not familiar with zope.testrunner.

We should at least update that docstring to mention that `setup.py test` is generally considered to be deprecated and should not be used.

**Comment by icemac** [comment]
Fixed in #14
